src/commands/8ball.js
src/commands/order.js
src/commands/quotes.js
src/commands/seen.js

.seen @ user
.8ball [question]
.order etc
.quote add [quote]
.quote random
.quote read [number]

dot commands for 8ball, order, quote, and seen

---

src/aquarius.js
src/client.js
src/commands/8ball.js
src/commands/broadcast.js
src/commands/choose.js
src/commands/karma.js
src/commands/order.js
src/commands/quotes.js
src/commands/seen.js
src/commands/stats.js
src/util/triggers.js

This is a more robust system that we can work with moving forward

Adds Message Triggers

---

src/commands/weather.js

Made emoji clarifications and added a few new emojis

---

package.json
src/commands/hearthstone.js

Adds hearthstone command and includes dependency hearthstone-db

added hearthstone command

---

src/commands/channels.js

Adds ability to be able to react to messages

Adds permissions for Aquarius-moderated channels

---

src/commands/fizzbuzz.js

Calls into my Rust fizzbuzz service to determine fizzbuzzness of the input number.

Add web-scale fizzbuzz.

---

src/commands/reply.js

```
[5:11 PM] cheshyre: .reply add "A" "b"
[5:11 PM] BOTAquarius: Added reply.
[5:11 PM] BOTAquarius-CDev: Added reply.
[5:11 PM] cheshyre: a
[5:11 PM] BOTAquarius: b
[5:11 PM] BOTAquarius-CDev: b
[5:12 PM] cheshyre: A
[5:12 PM] BOTAquarius: b
[5:12 PM] BOTAquarius-CDev: b
[5:12 PM] cheshyre: .reply remove "a"
[5:12 PM] BOTAquarius: Could not find a reply with 'a'
[5:12 PM] BOTAquarius-CDev: Removed 'a' reply
```

Shift case-invariance into DB query as requested.

---

src/commands/reply.js

Fixed regex to handle newlines(and other whitespace characters) for reply commands. So users can make more fun reply messages

Updated Regex to handle newlines in replies

---

.eslintrc
now.json
package.json
src/bot/commands/weather.js
src/global/commands/info.js
src/lib/metrics/users.js
web/metrics.js
yarn.lock

Fixes floating point number by wrapping with Math.round
Also adds a Celsius portion to temperatures. Another option would be to add the auto flag to our request, but would run into an issue for having F or C in text.

Fix Floating Points/Add Celsius

---

src/bot/commands/karma.js

Fix grammar issue. Fixes #345

---

packages/aquarius/src/bot/plugins/hashtag.js

this is probably a more contentious change than the nice change

hashtags start at word boundaries

---

package-lock.json
package.json
packages/aquarius/src/aquarius.js
packages/aquarius/src/bot/plugins/areki.js
packages/aquarius/src/global/commands/broadcast.js
packages/users/users.js

Untested because Windows is being difficult

Fix Broadcast v12

---

package-lock.json

Aight no more pushing straight to master for Ian

Fix Nested Packages

---

packages/aquarius/src/bot/plugins/nice.js

add emoji 69 to nice.js checks

---

packages/aquarius/src/bot/commands/deschtimes.js

Deschtimesv2

---

packages/aquarius/src/aquarius.js
packages/aquarius/src/bot/plugins/same.js
packages/aquarius/src/global/commands/quiet.js
packages/sentry/sentry.js

Correctly Apply Sentry Scope

---

package-lock.json
packages/aquarius/package.json
packages/aquarius/src/bot/commands/reminders.js
prisma/migrations/20210415043339_add_reminders/migration.sql
prisma/schema.prisma

Fixes #235
Also fixes #9 which is kinda cool

Add Reminders Command

---

packages/aquarius/src/aquarius.js

Hopefully I did this correctly! Haven't messed around with classes too much.

Prevent malicious mentions in commands

---

packages/aquarius/src/bot/commands/strawpoll.js

Strawpoll is the product-name which needs proper **CAPITALISATION**

capitalisation

---

packages/aquarius/src/bot/commands/cat.js

Switch to thecatapi.com
